language: node_js
node_js:
  - 8.0
  - 10.2.1
before_script:
  - npm dedupe
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
sudo: false
script:
  - npm run jshint
  - npm run test:browser
  - npm run coverage:upload
