language: node_js
node_js:
  - 8
  - 13.5.0
before_script:
  - npm dedupe
sudo: false
script:
  - npm run jshint
  - 'npm run test:browser'
  - 'npm run coverage:upload'
dist: xenial
services:
  - xvfb
